#!/usr/bin/env python3
"""Ensure the PowerShell profile loads scripts/dotfiles assets via env vars."""
from __future__ import annotations

import argparse
import re
from pathlib import Path


def _pwsh_profile_paths() -> list[Path]:
    """Return both pwsh and Windows PowerShell profile locations."""
    docs = Path.home() / "Documents"
    return [
        docs / "PowerShell" / "Microsoft.PowerShell_profile.ps1",
        docs / "WindowsPowerShell" / "Microsoft.PowerShell_profile.ps1",
    ]


def _profile_block() -> str:
    """PowerShell snippet that always references env-based repo paths."""
    lines = [
        "# ----- added by setup_pwsh_profile.py -----",
        "$dotfilesRoot = if ($env:DOTFILES_REPO) { $env:DOTFILES_REPO } "
        "elseif ($env:DOTFILES) { $env:DOTFILES } else { Join-Path $HOME 'dotfiles' }",
        "if ($dotfilesRoot) {",
        "    $dynamicDir = Join-Path $dotfilesRoot 'dynamic'",
        "    if (Test-Path (Join-Path $dynamicDir 'setup_pyscripts_aliases.ps1')) "
        "{ . (Join-Path $dynamicDir 'setup_pyscripts_aliases.ps1') }",
        "    if (Test-Path (Join-Path $dynamicDir 'setup_pyscripts_functions.ps1')) "
        "{ . (Join-Path $dynamicDir 'setup_pyscripts_functions.ps1') }",
        "    if (Test-Path (Join-Path $dynamicDir 'venv_auto_activation.ps1')) "
        "{ . (Join-Path $dynamicDir 'venv_auto_activation.ps1') }",
        "}",
        "$scriptsRoot = if ($env:SCRIPTS_REPO) { $env:SCRIPTS_REPO } "
        "elseif ($env:SCRIPTS) { $env:SCRIPTS } else { $null }",
        "if ($scriptsRoot) {",
        "    $clipboardModule = Join-Path $scriptsRoot 'pwsh\\ClipboardModule.psm1'",
        "    if (Test-Path $clipboardModule) { Import-Module $clipboardModule -ErrorAction SilentlyContinue }",
        "}",
        "# ----- end added by setup_pwsh_profile.py -----",
        "",
    ]
    return "\n".join(lines)


_MANAGED_BLOCK_RE = re.compile(
    r"# ----- added by setup_pwsh_profile\.py -----.*?# ----- end added by setup_pwsh_profile\.py -----\n?",
    flags=re.S,
)


def _update_profile(profile_path: Path, snippet: str, verbose: bool = False) -> None:
    """Replace or append the managed block in the given PowerShell profile."""
    existing = profile_path.read_text(encoding="utf-8") if profile_path.exists() else ""
    if _MANAGED_BLOCK_RE.search(existing):
        new_content = _MANAGED_BLOCK_RE.sub(snippet, existing, count=1)
        action = "updated" if new_content != existing else "unchanged"
    elif existing:
        new_content = existing.rstrip() + "\n\n" + snippet
        action = "appended"
    else:
        new_content = snippet
        action = "created"

    profile_path.parent.mkdir(parents=True, exist_ok=True)
    profile_path.write_text(new_content, encoding="utf-8")
    if verbose:
        print(f"[INFO] {profile_path} {action}")


def _write_venv_auto_activation(dyn_dir: Path, verbose: bool = False) -> None:
    """Emit dotfiles/dynamic/venv_auto_activation.ps1."""
    target = dyn_dir / "venv_auto_activation.ps1"
    target.parent.mkdir(parents=True, exist_ok=True)
    contents = """# Auto-generated by scripts_setup/setup_pwsh_profile.py
# Activates scripts/.venv when entering the repo (env-aware).

$script:__ScriptsVenvInfo = $null
$script:__ScriptsVenvSubscription = $null

function Initialize-ScriptsRepoVenvState {
    $scriptsRoot = if ($env:SCRIPTS_REPO) { $env:SCRIPTS_REPO } elseif ($env:SCRIPTS) { $env:SCRIPTS } else { $null }
    if (-not $scriptsRoot) { return }
    try {
        $resolvedRoot = (Resolve-Path -LiteralPath $scriptsRoot -ErrorAction Stop).Path
    } catch {
        return
    }

    $venvRoot = Join-Path $resolvedRoot ".venv"
    $activate = Join-Path $venvRoot "Scripts\\Activate.ps1"
    if (-not (Test-Path -LiteralPath $activate)) { return }

    $script:__ScriptsVenvInfo = [ordered]@{
        RepoPath = $resolvedRoot
        VenvRoot = $venvRoot
        Activate = $activate
        LastPath = $null
    }
}

function Invoke-ScriptsRepoVenv {
    if (-not $script:__ScriptsVenvInfo) { return }
    $current = (Get-Location).ProviderPath
    if ($script:__ScriptsVenvInfo.LastPath -eq $current) { return }
    $script:__ScriptsVenvInfo.LastPath = $current

    $repoPath = $script:__ScriptsVenvInfo.RepoPath
    $venvRoot = $script:__ScriptsVenvInfo.VenvRoot
    $insideRepo = $current.StartsWith($repoPath, [System.StringComparison]::OrdinalIgnoreCase)
    $venvActive = $env:VIRTUAL_ENV -and $env:VIRTUAL_ENV.StartsWith($venvRoot, [System.StringComparison]::OrdinalIgnoreCase)

    if ($insideRepo -and -not $venvActive) {
        . $script:__ScriptsVenvInfo.Activate | Out-Null
        Write-Host "[venv] Activated scripts/.venv" -ForegroundColor DarkGray
    } elseif (-not $insideRepo -and $venvActive) {
        if (Get-Command deactivate -ErrorAction SilentlyContinue) {
            deactivate | Out-Null
            Write-Host "[venv] Deactivated scripts/.venv" -ForegroundColor DarkGray
        }
    }
}

if (Get-EventSubscriber -SourceIdentifier 'ScriptsRepo.AutoVenv' -ErrorAction SilentlyContinue) {
    Get-EventSubscriber -SourceIdentifier 'ScriptsRepo.AutoVenv' |
        ForEach-Object { Unregister-Event -SubscriptionId $_.SubscriptionId -ErrorAction SilentlyContinue }
}

Initialize-ScriptsRepoVenvState
if ($script:__ScriptsVenvInfo) {
    $script:__ScriptsVenvSubscription = Register-EngineEvent -SourceIdentifier PowerShell.OnIdle `
        -Action { Invoke-ScriptsRepoVenv } -SupportEvent
    Invoke-ScriptsRepoVenv
} else {
    Write-Verbose "[venv-auto] scripts repo or .venv missing; skipping auto activation."
}
"""
    target.write_text(contents.strip() + "\n", encoding="utf-8")
    if verbose:
        print(f"[INFO] Wrote {target}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Add env-aware snippets to PowerShell profiles.")
    parser.add_argument("--scripts-dir", type=Path, required=True)
    parser.add_argument("--dotfiles-dir", type=Path, required=True)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    snippet = _profile_block()
    for profile in _pwsh_profile_paths():
        try:
            _update_profile(profile, snippet, verbose=args.verbose)
            print(f"[OK] Ensured profile block in {profile}")
        except Exception as exc:
            print(f"[WARN] Could not update {profile}: {exc}")

    dyn_dir = (args.dotfiles_dir / "dynamic").resolve()
    try:
        _write_venv_auto_activation(dyn_dir, verbose=args.verbose)
    except Exception as exc:
        print(f"[WARN] Could not write venv_auto_activation.ps1: {exc}")


if __name__ == "__main__":
    main()
