#!/usr/bin/env python3
"""Emit pwsh helper snippets without rewriting tracked profile files."""
from __future__ import annotations

import argparse
from pathlib import Path


def _profile_block(scripts_root: Path) -> str:
    """PowerShell snippet consumed by CustomProfile.ps1."""
    resolved_scripts = scripts_root.resolve()
    snippet = f"""# Auto-generated by scripts_setup/setup_pwsh_profile.py
$scriptsRoot = $null
if ($global:SCRIPTS_REPO -and (Test-Path $global:SCRIPTS_REPO -PathType Container)) {{
    $scriptsRoot = $global:SCRIPTS_REPO
}} elseif ($env:SCRIPTS_REPO -and (Test-Path $env:SCRIPTS_REPO -PathType Container)) {{
    $scriptsRoot = $env:SCRIPTS_REPO
}} elseif ($env:SCRIPTS -and (Test-Path $env:SCRIPTS -PathType Container)) {{
    $scriptsRoot = $env:SCRIPTS
}} elseif (Test-Path '{resolved_scripts}' -PathType Container) {{
    $scriptsRoot = '{resolved_scripts}'
}}

if ($scriptsRoot) {{
    try {{
        $resolvedScripts = (Resolve-Path -LiteralPath $scriptsRoot -ErrorAction Stop).Path
        $clipboardModule = Join-Path $resolvedScripts 'pwsh\\ClipboardModule.psm1'
        if (Test-Path $clipboardModule) {{
            Import-Module $clipboardModule -ErrorAction SilentlyContinue
        }}
    }} catch {{
        Write-Debug 'setup_pwsh_profile: failed to resolve scripts repo path.' -Channel Information -Condition $global:DebugProfile
    }}
}} else {{
    Write-Debug 'setup_pwsh_profile: scripts repo not detected; skipping ClipboardModule.' -Channel Information -Condition $global:DebugProfile
}}
"""
    return snippet.strip() + "\n"


def _write_profile_snippet(dyn_dir: Path, snippet: str, verbose: bool = False) -> None:
    """Write the snippet that CustomProfile.ps1 dot-sources."""
    target = dyn_dir / "setup_pwsh_profile.generated.ps1"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(snippet, encoding="utf-8")
    if verbose:
        print(f"[INFO] Wrote {target}")


def _write_venv_auto_activation(dyn_dir: Path, verbose: bool = False) -> None:
    """Emit dotfiles/dynamic/venv_auto_activation.ps1."""
    target = dyn_dir / "venv_auto_activation.ps1"
    target.parent.mkdir(parents=True, exist_ok=True)
    contents = """# Auto-generated by scripts_setup/setup_pwsh_profile.py
# Activates scripts/.venv when entering the repo (env-aware).

$script:__ScriptsVenvInfo = $null
$script:__ScriptsVenvSubscription = $null

function Initialize-ScriptsRepoVenvState {
    $scriptsRoot = if ($env:SCRIPTS_REPO) { $env:SCRIPTS_REPO } elseif ($env:SCRIPTS) { $env:SCRIPTS } else { $null }
    if (-not $scriptsRoot) { return }
    try {
        $resolvedRoot = (Resolve-Path -LiteralPath $scriptsRoot -ErrorAction Stop).Path
    } catch {
        return
    }

    $venvRoot = Join-Path $resolvedRoot ".venv"
    $activate = Join-Path $venvRoot "Scripts\\Activate.ps1"
    if (-not (Test-Path -LiteralPath $activate)) { return }

    $script:__ScriptsVenvInfo = [ordered]@{
        RepoPath = $resolvedRoot
        VenvRoot = $venvRoot
        Activate = $activate
        LastPath = $null
    }
}

function Invoke-ScriptsRepoVenv {
    if (-not $script:__ScriptsVenvInfo) { return }
    $current = (Get-Location).ProviderPath
    if ($script:__ScriptsVenvInfo.LastPath -eq $current) { return }
    $script:__ScriptsVenvInfo.LastPath = $current

    $repoPath = $script:__ScriptsVenvInfo.RepoPath
    $venvRoot = $script:__ScriptsVenvInfo.VenvRoot
    $insideRepo = $current.StartsWith($repoPath, [System.StringComparison]::OrdinalIgnoreCase)
    $venvActive = $env:VIRTUAL_ENV -and $env:VIRTUAL_ENV.StartsWith($venvRoot, [System.StringComparison]::OrdinalIgnoreCase)

    if ($insideRepo -and -not $venvActive) {
        . $script:__ScriptsVenvInfo.Activate | Out-Null
        Write-Host "[venv] Activated scripts/.venv" -ForegroundColor DarkGray
    } elseif (-not $insideRepo -and $venvActive) {
        if (Get-Command deactivate -ErrorAction SilentlyContinue) {
            deactivate | Out-Null
            Write-Host "[venv] Deactivated scripts/.venv" -ForegroundColor DarkGray
        }
    }
}

if (Get-EventSubscriber -SourceIdentifier 'ScriptsRepo.AutoVenv' -ErrorAction SilentlyContinue) {
    Get-EventSubscriber -SourceIdentifier 'ScriptsRepo.AutoVenv' |
        ForEach-Object { Unregister-Event -SubscriptionId $_.SubscriptionId -ErrorAction SilentlyContinue }
}

Initialize-ScriptsRepoVenvState
if ($script:__ScriptsVenvInfo) {
    $script:__ScriptsVenvSubscription = Register-EngineEvent -SourceIdentifier PowerShell.OnIdle `
        -Action { Invoke-ScriptsRepoVenv } -SupportEvent
    Invoke-ScriptsRepoVenv
} else {
    Write-Verbose "[venv-auto] scripts repo or .venv missing; skipping auto activation."
}
"""
    target.write_text(contents.strip() + "\n", encoding="utf-8")
    if verbose:
        print(f"[INFO] Wrote {target}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Add env-aware snippets to PowerShell profiles.")
    parser.add_argument("--scripts-dir", type=Path, required=True)
    parser.add_argument("--dotfiles-dir", type=Path, required=True)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    dyn_dir = (args.dotfiles_dir / "dynamic").resolve()
    snippet = _profile_block(args.scripts_dir)
    try:
        _write_profile_snippet(dyn_dir, snippet, verbose=args.verbose)
        print(f"[OK] Wrote setup snippet to {dyn_dir}")
    except Exception as exc:
        print(f"[WARN] Could not write pwsh setup snippet: {exc}")

    try:
        _write_venv_auto_activation(dyn_dir, verbose=args.verbose)
    except Exception as exc:
        print(f"[WARN] Could not write venv_auto_activation.ps1: {exc}")


if __name__ == "__main__":
    main()
