"""String templates for agent_sync generated Markdown documents."""

SESSION_BRIEF = """\
---
schema: agent_sync/session_brief/v1
task_id: {task_id}
run_id: {run_id}
agent: {agent_name}
branch: {branch_name}
worktree: {worktree_path}
generated_at: {generated_at}
---

# Session Brief — {task_id}

## What You Are Doing

{summary_md}

## Current Status

- Task status: **{task_status}**
- This run: **{run_id}** ({agent_name}, {mode})
- Branch: `{branch_name}`
- Worktree: `{worktree_path}`

## Claimed Files

{claims_section}

## Acceptance Commands

{acceptance_md}

## Open Issues / Handoff Context

{handoff_context}

---
*Generated by agent_sync. Treat repo state as authoritative over any prior session memory.*
"""

HANDOFF = """\
---
schema: agent_sync/handoff/v1
task_id: {task_id}
from_run_id: {from_run_id}
from_agent: {from_agent}
to_agent: {to_agent}
status: ready_for_resume
created_at: {created_at}
target_branch: {target_branch}
work_branch: {work_branch}
worktree_path: {worktree_path}
---

# Handoff — {task_id}

## Objective

{summary_md}

## What Changed

{changed_files_section}

## Validation State

{validation_section}

## Blocking Issues

{blocking_issues}

## Open Questions

{open_questions}

## Next Steps

{next_steps}

## Integration Notes

{integration_notes}

---
*To continue: `agent-sync resume -t {task_id}` or read this file and proceed from repo state.*
"""

AGENT_CONTRACT = """\
# Agent Contract

This repository uses `agent_sync` for deterministic multi-agent coordination.

## Always Read First

- `agent_sync/docs/SESSION_BRIEF.md`
- `agent_sync/docs/HANDOFF.md`
- `agent_sync/docs/AGENT_CONTRACT.md`

## Rules

- Use repo state, not prior chat memory, as the source of truth.
- Do not write mutable orchestration state into `.claude/`, `.codex/`, or `.gemini/`.
- When stopping, ensure HANDOFF.md is complete enough for another agent to continue.
- Confirm your assigned task_id and claimed files from SESSION_BRIEF.md before editing.
- If parallel work is needed, create child task manifests (`agent-sync dispatch`).
- Do not commit directly to the target branch; work on your task branch only.
- `agent-sync integrate` is the only path to merge your branch.
- If blocked, write the block reason and exact next step into HANDOFF.md before stopping.

## Forbidden Commands (handled by hooks + provider rules)

- `git push` (use `agent-sync integrate`)
- `git commit` on target branch
- `gh pr create` / `gh pr merge`
- `rm -rf`, `sudo`
- Writes to `.env`, `*.key`, `*.pem`, credential files
- DB migrations against non-local environments
"""

AGENTS_MD_SECTION = """

## agent_sync coordination

Read these files before making changes:

- `agent_sync/docs/SESSION_BRIEF.md`
- `agent_sync/docs/HANDOFF.md`
- `agent_sync/docs/AGENT_CONTRACT.md`

Treat `agent_sync/db/state.sqlite3` and `agent_sync/docs/` as the current source
of truth. Do not invent project state from chat history when the repo disagrees.
"""

CLAUDE_MD_SECTION = """

## agent_sync coordination

This repository uses `agent_sync` for deterministic coordination.

Always read:

- `agent_sync/docs/SESSION_BRIEF.md`
- `agent_sync/docs/HANDOFF.md`
- `agent_sync/docs/AGENT_CONTRACT.md`

Use repo-local state, not prior chat memory, as the source of truth.
Do not store mutable handoff state in `.claude/`.
When stopping, ensure HANDOFF.md is complete enough for another agent to continue.
"""

GEMINI_MD_SECTION = CLAUDE_MD_SECTION.replace(".claude/", ".gemini/")
