# mypysetup/projects.py
from __future__ import annotations
from pathlib import Path
from typing import Optional
from .installer import which, call

def create_project(
    name: str,
    kind: str = "uv",      # "uv" | "venv" | "none"
    venv_dir: Optional[str] = ".venv",
) -> dict:
    root = Path(name).resolve()
    result = {"created": [], "messages": []}

    if root.exists():
        result["messages"].append(f"Project folder exists: {root}")
    else:
        root.mkdir(parents=True, exist_ok=True)
        result["created"].append(str(root))

    (root / "README.md").write_text(f"# {name}\n\nGenerated by mypysetup.\n", encoding="utf-8")
    (root / ".gitignore").write_text(".venv/\n__pycache__/\n*.pyc\n", encoding="utf-8")

    if kind == "uv":
        if which("uv"):
            rc, out, err = call(["uv","init",str(root)])
            if rc==0:
                rc2, out2, err2 = call(["uv","sync"])
                if rc2==0:
                    result["messages"].append("uv project initialized and synced.")
                else:
                    result["messages"].append(f"uv sync failed: {err2}")
            else:
                result["messages"].append(f"uv init failed: {err}")
        else:
            result["messages"].append("uv not found; falling back to stdlib venv.")
            kind = "venv"

    if kind == "venv":
        py = which("python") or which("python3")
        if not py:
            result["messages"].append("No python found to create venv.")
        else:
            vdir = root / (venv_dir or ".venv")
            rc, out, err = call([py,"-m","venv",str(vdir)])
            if rc==0:
                result["messages"].append(f"Created venv at {vdir}")
            else:
                result["messages"].append(f"venv creation failed: {err}")

    pyp = root / "pyproject.toml"
    if not pyp.exists():
        pyp.write_text(
            '[project]\nname = "%s"\nversion = "0.1.0"\nrequires-python = ">=3.9"\n' % name,
            encoding="utf-8"
        )
        result["created"].append(str(pyp))
    return result
