"""Public exports for path_manager."""

from .core import (
    CommandRecord,
    WriteResult,
    SCOPE_MACHINE,
    SCOPE_PROCESS,
    SCOPE_USER,
    analyze_resolution_changes,
    backup_all,
    build_command_index,
    build_new_string,
    build_resolution_map,
    coerce_to_directory,
    compute_diff,
    get_backup_dir,
    get_combined_segments,
    get_invalid_segments,
    get_pathexts,
    list_executables_in_dir,
    load_backup,
    normalize_segments,
    read_path,
    resolve_scope,
    safe_write_path,
    split_path_string,
    split_tokens_loose,
    write_path,
)

__all__ = [
    "CommandRecord",
    "WriteResult",
    "SCOPE_MACHINE",
    "SCOPE_PROCESS",
    "SCOPE_USER",
    "analyze_resolution_changes",
    "backup_all",
    "build_command_index",
    "build_new_string",
    "build_resolution_map",
    "coerce_to_directory",
    "compute_diff",
    "get_backup_dir",
    "get_combined_segments",
    "get_invalid_segments",
    "get_pathexts",
    "list_executables_in_dir",
    "load_backup",
    "normalize_segments",
    "read_path",
    "resolve_scope",
    "safe_write_path",
    "split_path_string",
    "split_tokens_loose",
    "write_path",
]
