"""Constants used across runmux."""

from __future__ import annotations

APP_NAME = "runmux"
DEFAULT_REFRESH_SECONDS = 1.0
DEFAULT_SOCKET_TIMEOUT_SECONDS = 2.0
DEFAULT_STARTUP_TIMEOUT_SECONDS = 15.0
ATTACH_RESERVED_ROWS = 1
DEFAULT_CONTROL_PREFIX = b"\x18"
DEFAULT_CONTROL_PREFIX_NAME = "Ctrl-X"
STATUS_PENDING = "pending"
STATUS_RUNNING = "running"
STATUS_FINISHED = "finished"
STATUS_FAILED = "failed"
STATUS_KILLED = "killed"
STATUS_PAUSED = "paused"
STATUS_LOST = "lost"
TERMINAL_STATUSES = {STATUS_FINISHED, STATUS_FAILED, STATUS_KILLED, STATUS_LOST}
ACTIVE_STATUSES = {STATUS_PENDING, STATUS_RUNNING, STATUS_PAUSED}
